# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2991705f8839341772e3717c993c7ce7e1494cfc13b3f6583465964fcadb0c928136a6e39aebf01d07311a3b10b6ad3321dc0eb2b4dd7cd9fb2c087815e8ce0

test:
  secret_key_base: 929e104932b4ed89bbe14f200359f39c6ac2e2bdc67c1885da463c4ec8ac4fb772a7f4490c7e0d05ee86bf864413eacee3dad06ea5104201815c3aa57ebbf2e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
